// Generated by CoffeeScript 1.10.0
(function() {
  var Consumer, HMAC_SHA1, MemoryNonceStore, crypto, errors, exports, extensions,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  crypto = require('crypto');

  HMAC_SHA1 = require('./hmac-sha1');

  MemoryNonceStore = require('./memory-nonce-store');

  errors = require('./errors');

  extensions = require('./extensions');

  Consumer = (function() {
    function Consumer(consumer_key, consumer_secret, nonceStore, signature_method) {
      if (signature_method == null) {
        signature_method = new HMAC_SHA1();
      }
      this.encode_request = bind(this.encode_request, this);
      if (typeof consumer_key === 'undefined' || consumer_key === null) {
        throw new errors.ConsumerError('Must specify consumer_key');
      }
      if (typeof consumer_secret === 'undefined' || consumer_secret === null) {
        throw new errors.ConsumerError('Must specify consumer_secret');
      }
      if (!nonceStore) {
        nonceStore = new MemoryNonceStore();
      }
      if (!(typeof nonceStore.isNonceStore === "function" ? nonceStore.isNonceStore() : void 0)) {
        throw new errors.ParameterError('Fourth argument must be a nonceStore object');
      }
      this.consumer_key = consumer_key;
      this.consumer_secret = consumer_secret;
      this.signer = signature_method;
      this.nonceStore = nonceStore;
      this.body = {};
    }

    Consumer.prototype.encode_request = function(urlInfo, body, callback) {
      var sig;
      if (!callback) {
        callback = body;
        body = void 0;
      }
      callback = callback || function() {};
      body.oauth_nonce = crypto.randomBytes(Math.ceil(16)).toString('hex').slice(0, 32);
      body.oauth_consumer_key = this.consumer_key;
      body.oauth_signature_method = 'HMAC-SHA1';
      body.oauth_timestamp = Math.floor(new Date() / 1000);
      body.oauth_version = '1.0';
      body.oauth_callback = 'about:blank';
      sig = this.signer.build_signature(urlInfo, body, this.consumer_secret);
      body.oauth_signature = sig;
      return callback(null, body);
    };

    return Consumer;

  })();

  exports = module.exports = Consumer;

}).call(this);
